version: "2"
volumes:
  data-peer0.events:
  data-peer1.events:
  data-peer0.promotion:
  data-peer1.promotion:
  data-peer0.registeration:
  data-peer1.registeration:
  data-peer0.sports:
  data-peer1.sports:
  data-peer0.sportsfemale:
  data-peer1.sportsfemale:
  data-orderer:
networks:
  voting:
services:
  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_LOCALMSPID=OrdererMSP
    volumes:
      - ./config/orderer:/var/hyperledger/config
      - .\config\crypto-config\ordererOrganizations\example.com\orderers\orderer.example.com\msp:/var/hyperledger/msp
      - .\config\crypto-config\ordererOrganizations\example.com\orderers\orderer.example.com\tls:/var/hyperledger/tls
      - data-orderer:/var/ledger
    ports:
      - "7050:7050"
      - "7051:7051"
    command: orderer
    networks:
      - voting

  peer0.events.example.com:
    container_name: peer0.events.example.com
    image: hyperledger/fabric-peer
    working_dir: /opt/gopath/src/github.com/vote
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_LOCALMSPID=EventsMSP
      - CORE_PEER_ID=peer0.events.example.com
      - CORE_PEER_ADDRESS=peer0.events.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.events.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.events.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer1.events.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.events.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\events.example.com\users\Admin@events.example.com\msp:/var/hyperledger/msp
      - .\config/crypto-config/peerOrganizations/events.example.com/peers/peer0.events.example.com/tls:/var/hyperledger/tls

      # ! Production data storage!!!! DONOT REMOVE
      - data-peer0.events:/var/hyperledger/production
    ports:
      - "7052:7051"
      - "7053:7052"
    command: peer node start
    networks:
      - voting
    depends_on:
      - orderer.example.com

  peer1.events.example.com:
    container_name: peer1.events.example.com
    image: hyperledger/fabric-peer
    working_dir: /opt/gopath/src/github.com/vote
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_LOCALMSPID=EventsMSP
      - CORE_PEER_ID=peer1.events.example.com
      - CORE_PEER_ADDRESS=peer1.events.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.events.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.events.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer0.events.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.events.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\events.example.com\users\User1@events.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/events.example.com/peers/peer1.events.example.com/tls:/var/hyperledger/tls
      - data-peer1.events:/var/hyperledger/production
    ports:
      - "7054:7051"
      - "7055:7052"
    command: peer node start
    networks:
      - voting
    depends_on:
      - orderer.example.com

  peer0.promotion.example.com:
    container_name: peer0.promotion.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer0.promotion.example.com
      - CORE_PEER_ADDRESS=peer0.promotion.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.promotion.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.promotion.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer1.promotion.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.promotion.example.com:7051
      - CORE_PEER_LOCALMSPID=PromotionMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\promotion.example.com\users\Admin@promotion.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/promotion.example.com/peers/peer0.promotion.example.com/tls:/var/hyperledger/tls
      - data-peer0.promotion:/var/hyperledger/production
    ports:
      - "7056:7051"
      - "7057:7052"
    command: peer node start
    networks:
      - voting

  peer1.promotion.example.com:
    container_name: peer1.promotion.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer1.promotion.example.com
      - CORE_PEER_ADDRESS=peer1.promotion.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.promotion.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.promotion.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer0.promotion.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.promotion.example.com:7051
      - CORE_PEER_LOCALMSPID=PromotionMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\promotion.example.com\users\User1@promotion.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/promotion.example.com/peers/peer1.promotion.example.com/tls:/var/hyperledger/tls
      - data-peer1.promotion:/var/hyperledger/production
    ports:
      - "7058:7051"
      - "7059:7052"
    command: peer node start
    networks:
      - voting

  peer0.registeration.example.com:
    container_name: peer0.registeration.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer0.registeration.example.com
      - CORE_PEER_ADDRESS=peer0.registeration.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.registeration.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.registeration.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer1.registeration.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.registeration.example.com:7051
      - CORE_PEER_LOCALMSPID=RegisterationMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\registeration.example.com\users\Admin@registeration.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/registeration.example.com/peers/peer0.registeration.example.com/tls:/var/hyperledger/tls
      - data-peer0.registeration:/var/hyperledger/production
    ports:
      - "7060:7051"
      - "7061:7052"
    command: peer node start
    networks:
      - voting

  peer1.registeration.example.com:
    container_name: peer1.registeration.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer1.registeration.example.com
      - CORE_PEER_ADDRESS=peer1.registeration.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.registeration.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.registeration.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer0.registeration.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.registeration.example.com:7051
      - CORE_PEER_LOCALMSPID=RegisterationMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\registeration.example.com\users\User1@registeration.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/registeration.example.com/peers/peer1.registeration.example.com/tls:/var/hyperledger/tls
      - data-peer1.registeration:/var/hyperledger/production
    ports:
      - "7062:7051"
      - "7063:7052"
    command: peer node start
    networks:
      - voting

  peer0.sports.example.com:
    container_name: peer0.sports.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer0.sports.example.com
      - CORE_PEER_ADDRESS=peer0.sports.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sports.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sports.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer1.sports.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sports.example.com:7051
      - CORE_PEER_LOCALMSPID=SportsMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\sports.example.com\users\Admin@sports.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/sports.example.com/peers/peer0.sports.example.com/tls:/var/hyperledger/tls
      - data-peer0.sports:/var/hyperledger/production
    ports:
      - "7064:7051"
      - "7065:7052"
    command: peer node start
    networks:
      - voting

  peer1.sports.example.com:
    container_name: peer1.sports.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer1.sports.example.com
      - CORE_PEER_ADDRESS=peer1.sports.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.sports.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sports.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer1.sports.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sports.example.com:7051
      - CORE_PEER_LOCALMSPID=SportsMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\sports.example.com\users\User1@sports.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/sports.example.com/peers/peer1.sports.example.com/tls:/var/hyperledger/tls
      - data-peer1.sports:/var/hyperledger/production
    ports:
      - "7066:7051"
      - "7067:7052"
    command: peer node start
    networks:
      - voting

  peer0.sportsfemale.example.com:
    container_name: peer0.sportsfemale.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer0.sportsfemale.example.com
      - CORE_PEER_ADDRESS=peer0.sportsfemale.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sportsfemale.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sportsfemale.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer1.sportsfemale.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sportsfemale.example.com:7051
      - CORE_PEER_LOCALMSPID=SportsFemaleMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\sportsfemale.example.com\users\Admin@sportsfemale.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/sportsfemale.example.com/peers/peer0.sportsfemale.example.com/tls:/var/hyperledger/tls
      - data-peer0.sportsfemale:/var/hyperledger/production
    ports:
      - "7068:7051"
      - "7069:7052"
    command: peer node start
    networks:
      - voting

  peer1.sportsfemale.example.com:
    container_name: peer1.sportsfemale.example.com
    image: hyperledger/fabric-peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - CORE_PEER_ID=peer1.sportsfemale.example.com
      - CORE_PEER_ADDRESS=peer1.sportsfemale.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.sportsfemale.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sportsfemale.example.com:7051
      # - CORE_PEER_GOSSIP_ENDPOINT=peer0.sportsfemale.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sportsfemale.example.com:7051
      - CORE_PEER_LOCALMSPID=SportsFemaleMSP
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_voting
    volumes:
      - ./config/peer:/var/hyperledger/config
      - .\config\crypto-config\peerOrganizations\sportsfemale.example.com\users\User1@sportsfemale.example.com\msp:/var/hyperledger/msp
      - ./config/crypto-config/peerOrganizations/sportsfemale.example.com/peers/peer1.sportsfemale.example.com/tls:/var/hyperledger/tls
      - data-peer1.sportsfemale:/var/hyperledger/production
    ports:
      - "7070:7051"
      - "7071:7052"
    command: peer node start
    networks:
      - voting
  tools:
    container_name: tools
    command: /bin/bash

    # Tools container image
    image: hyperledger/fabric-tools

    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
    # This is the working directory on login
    working_dir: /opt/scripts
    volumes:
      - ./chaincode:/opt/nodechaincode
      - ./config:/var/hyperledger/config
      - ./config/crypto-config/peerOrganizations:/var/hyperledger/crypto
      - ./scripts:/opt/scripts
    networks:
      - voting
