# CAPABILITES
Capabilities:
  Application: &ApplicationCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Channel: &ChannelCapabilities
    V2_0: true

Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ./crypto-config/ordererOrganizations/example.com/msp
    Policies: &OrdererPolicies
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        # NOTE: ONLY Admin Role can carry out administration activities
        Rule: "OR('OrdererMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
  - &Events
    Name: EventsMSP
    ID: EventsMSP
    MSPDir: ./crypto-config/peerOrganizations/events.example.com/msp
    AnchorPeers:
      - Host: peer0-events-clusterip
        Port: 30751
    Policies: &EventsPolicies
      Readers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.peer', 'AcmeMSP.client')"
        Rule: "OR('EventsMSP.member')"
      Writers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.client')"
        Rule: "OR('EventsMSP.member')"
      Admins:
        Type: Signature
        # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use AcmeMSP.admin
        Rule: "OR('EventsMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('EventsMSP.member')"

  - &Promotion
    Name: PromotionMSP
    ID: PromotionMSP
    MSPDir: ./crypto-config/peerOrganizations/promotion.example.com/msp
    AnchorPeers:
      - Host: peer0-promotion-clusterip
        Port: 30951
    Policies: &PromotionPolicies
      Readers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.peer', 'AcmeMSP.client')"
        Rule: "OR('PromotionMSP.member')"
      Writers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.client')"
        Rule: "OR('PromotionMSP.member')"
      Admins:
        Type: Signature
        # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use AcmeMSP.admin
        Rule: "OR('PromotionMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('PromotionMSP.member')"

  - &Registeration
    Name: RegisterationMSP
    ID: RegisterationMSP
    MSPDir: ./crypto-config/peerOrganizations/registeration.example.com/msp
    AnchorPeers:
      - Host: peer0-registeration-clusterip
        Port: 31151
    Policies: &RegisterationPolicies
      Readers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.peer', 'AcmeMSP.client')"
        Rule: "OR('RegisterationMSP.member')"
      Writers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.client')"
        Rule: "OR('RegisterationMSP.member')"
      Admins:
        Type: Signature
        # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use AcmeMSP.admin
        Rule: "OR('RegisterationMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegisterationMSP.member')"

  - &Sports
    Name: SportsMSP
    ID: SportsMSP
    MSPDir: ./crypto-config/peerOrganizations/sports.example.com/msp
    AnchorPeers:
      - Host: peer0-sports-clusterip
        Port: 31351
    Policies: &SportsPolicies
      Readers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.peer', 'AcmeMSP.client')"
        Rule: "OR('SportsMSP.member')"
      Writers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.client')"
        Rule: "OR('SportsMSP.member')"
      Admins:
        Type: Signature
        # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use AcmeMSP.admin
        Rule: "OR('SportsMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('SportsMSP.member')"

  - &SportsFemale
    Name: SportsFemaleMSP
    ID: SportsFemaleMSP
    MSPDir: ./crypto-config/peerOrganizations/sportsfemale.example.com/msp
    AnchorPeers:
      - Host: peer0-sportsfemale-clusterip
        Port: 31551
    Policies: &SportsFemalePolicies
      Readers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.peer', 'AcmeMSP.client')"
        Rule: "OR('SportsFemaleMSP.member')"
      Writers:
        Type: Signature
        #   Rule: "OR('AcmeMSP.admin', 'AcmeMSP.client')"
        Rule: "OR('SportsFemaleMSP.member')"
      Admins:
        Type: Signature
        # UPDATE: Dec 15, 2019 - This is a dev env so its OK in Prod ... use AcmeMSP.admin
        Rule: "OR('SportsFemaleMSP.member')"
      Endorsement:
        Type: Signature
        Rule: "OR('SportsFemaleMSP.member')"

Orderer: &OrdererDefaults
  OrdererType: solo

  Addresses:
    - orderer-clusterip:30750

  # Policies for Orderer
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      # UPDATED December 15, 2019
      Rule: "ANY Admins"
      # Rule: "MAJORITY Admins"

    # BlockValidation specifies what signatures must be included in the block
    # from the orderer for the peer to validate it.
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

  # Batch Timeout: The amount of time to wait before creating a batch
  BatchTimeout: 2s

  # Batch Size: Controls the number of messages batched into a block
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB

  Capabilities:
    <<: *OrdererCapabilities

Application: &ApplicationDefaults # Default policies
  Policies: &ApplicationDefaultPolicies # approveformyorg
    LifecycleEndorsement:
      Type: ImplicitMeta
      # Rule: "MAJORITY Endorsement"
      Rule: "ANY Endorsement"

    # --channel-config-policy
    Endorsement:
      Type: ImplicitMeta
      Rule: "ANY Endorsement"
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"

  Organizations:
  Capabilities:
    <<: *ApplicationCapabilities
  ACLs: &ACLsDefault # ACL policy for lscc's "getid" function
    lscc/ChaincodeExists: /Channel/Application/Readers

    # ACL policy for lscc's "getdepspec" function
    lscc/GetDeploymentSpec: /Channel/Application/Readers

    # ACL policy for lscc's "getccdata" function
    lscc/GetChaincodeData: /Channel/Application/Readers

    # ACL Policy for lscc's "getchaincodes" function
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers

    #---Query System Chaincode (qscc) function to policy mapping for access control---#

    # ACL policy for qscc's "GetChainInfo" function
    qscc/GetChainInfo: /Channel/Application/Readers

    # ACL policy for qscc's "GetBlockByNumber" function
    qscc/GetBlockByNumber: /Channel/Application/Readers

    # ACL policy for qscc's  "GetBlockByHash" function
    qscc/GetBlockByHash: /Channel/Application/Readers

    # ACL policy for qscc's "GetTransactionByID" function
    qscc/GetTransactionByID: /Channel/Application/Readers

    # ACL policy for qscc's "GetBlockByTxID" function
    qscc/GetBlockByTxID: /Channel/Application/Readers

    #---Configuration System Chaincode (cscc) function to policy mapping for access control---#

    # ACL policy for cscc's "GetConfigBlock" function
    cscc/GetConfigBlock: /Channel/Application/Readers

    # ACL policy for cscc's "GetConfigTree" function
    cscc/GetConfigTree: /Channel/Application/Readers

    # ACL policy for cscc's "SimulateConfigTreeUpdate" function
    cscc/SimulateConfigTreeUpdate: /Channel/Application/Readers

    #---Miscellanesous peer function to policy mapping for access control---#

    # ACL policy for invoking chaincodes on peer
    peer/Propose: /Channel/Application/Writers

    # ACL policy for chaincode to chaincode invocation
    peer/ChaincodeToChaincode: /Channel/Application/Readers

    #---Events resource to policy mapping for access control###---#

    # ACL policy for sending block events
    event/Block: /Channel/Application/Readers

    # ACL policy for sending filtered block events
    event/FilteredBlock: /Channel/Application/Readers

    # Chaincode Lifecycle Policies introduced in Fabric 2.x
    # ACL policy for _lifecycle's "CheckCommitReadiness" function
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers

    # ACL policy for _lifecycle's "CommitChaincodeDefinition" function
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers

    # ACL policy for _lifecycle's "QueryChaincodeDefinition" function
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Readers

#   CHANNEL
Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "ANY Admins"
  Capabilities:
    <<: *ChannelCapabilities

# Application configuration
Profiles:
  EVotingChannel:
    <<: *ChannelDefaults
    Consortium: EvotingConsortium

    Application:
      <<: *ApplicationDefaults

      Organizations:
        - <<: *Events
        - <<: *Promotion
        - <<: *Registeration
        - <<: *Sports
        - <<: *SportsFemale
  EVotingGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - <<: *OrdererOrg
    Consortiums:
      EvotingConsortium:
        Organizations:
          - <<: *Events
          - <<: *Promotion
          - <<: *Registeration
          - <<: *Sports
          - <<: *SportsFemale
