# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer1-registeration
  labels:
    app: peer1-registeration
spec:
  serviceName: peer1-registeration
  replicas: 1
  selector:
    matchLabels:
      app: peer1-registeration
  template:
    metadata:
      labels:
        app: peer1-registeration
    spec:
      containers:
        - name: peer1-registeration
          # Image used
          image: mutti11/peer1_registeration
          # Uncomment the following during development/testing of the image
          imagePullPolicy: Always
          env:
            - name: FABRIC_CFG_PATH
              value: /var/hyperledger/config
            - name: CORE_PEER_LOCALMSPID
              value: RegisterationMSP
            - name: CORE_PEER_ID
              value: peer1.registeration.example.com
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: ORDERER_ADDRESS
              value: orderer-clusterip:30750
            - name: ORG_CONTEXT
              value: registeration
            - name: CORE_PEER_ADDRESS
              value: peer1-registeration-clusterip:31251
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:31251
            - name: CORE_PEER_CHAINCODEADDRESS
              value: peer1-registeration-clusterip:31252
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer0-registeration-clusterip:31151
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer0-registeration-clusterip:31151
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: 0.0.0.0:31251
          volumeMounts:
            - name: peer1-registeration-ledger
              mountPath: /var/ledger
            - name: dockersock
              mountPath: /var/run/docker.sock
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
  volumeClaimTemplates:
    - metadata:
        name: peer1-registeration-ledger
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: general
        resources:
          requests:
            storage: 1Gi

---
# Expose the port 31251 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer1-registeration-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer1-registeration

  ports:
    - name: peer1-registeration-clusterip
      port: 31251
    - name: peer1-registeration-cc-clusterip
      port: 31252

  type: ClusterIP

---
# Expose the port 31251 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer1-registeration-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer1-registeration

  ports:
    - name: peer1-registeration-nodeport-751
      port: 31251
      nodePort: 31251
    - name: peer1-registeration-cc-nodeport-752
      port: 31252
      nodePort: 31252

  type: NodePort
