kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unauthenticated-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unauthenticated-binding
subjects:
  - kind: Group
    name: system:unauthenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: unauthenticated-role
  apiGroup: rbac.authorization.k8s.io
