# YAML for launching the orderer
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer0-events
  labels:
    app: peer0-events
spec:
  serviceName: peer0-events
  replicas: 1
  selector:
    matchLabels:
      app: peer0-events
  template:
    metadata:
      labels:
        app: peer0-events
    spec:
      containers:
        - name: peer0-events
          # Image used
          image: mutti11/peer0_events
          # Uncomment the following during development/testing of the image
          imagePullPolicy: Always
          env:
            - name: FABRIC_CFG_PATH
              value: /var/hyperledger/config
            - name: CORE_PEER_LOCALMSPID
              value: EventsMSP
            - name: CORE_PEER_ID
              value: peer0.events.example.com
            - name: FABRIC_LOGGING_SPEC
              value: INFO
            - name: ORDERER_ADDRESS
              value: orderer-clusterip:30750
            - name: ORG_CONTEXT
              value: events
            - name: CORE_PEER_ADDRESS
              value: localhost:30751
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:30751
            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:30752
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: peer1-events-clusterip:30851
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: peer1-events-clusterip:30851
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: 0.0.0.0:30751
          volumeMounts:
            - name: peer0-events-ledger
              mountPath: /var/ledger
            - name: dockersock
              mountPath: /var/run/docker.sock
              readOnly: true
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock

  volumeClaimTemplates:
    - metadata:
        name: peer0-events-ledger
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: general
        resources:
          requests:
            storage: 1Gi

---
# Expose the port 30751 as ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: peer0-events-clusterip

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer0-events

  ports:
    - name: peer0-events-clusterip
      port: 30751
    - name: peer0-events-cc-clusterip
      port: 30752

  type: ClusterIP

---
# Expose the port 30751 as node port -  NEEDED if you
# are interested in connecting to the Pods from the Host
# machine - keep in mind you would need the IP for the node
# port service
apiVersion: v1
kind: Service
metadata:
  name: peer0-events-nodeport

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: peer0-events

  ports:
    - name: peer0-events-nodeport-751
      port: 30751
      nodePort: 30751
    - name: peer0-events-cc-nodeport-752
      port: 30752
      nodePort: 30752

  type: NodePort
